### PR TITLE
Add polls remove option btn

### PR DESCRIPTION
**Pull request by jessxec**
Resolves issue #12 

The main branch kept throwing an error of "can't find ./serializer" in the `nodebb-plugin-poll-modified` folder when building, so I recopied the plugin directory. This fixed the build error. 

`nodebb-plugin-poll-modified/templates/poll/creator.tpl` was modified to add an input button for remove.
`nodebb-plugin-poll-modified/public/js/poll/creator.js` was modified for button interaction for the remove button. It only removes where there is more than one option in the creator.

### CODE REVIEW

**Review by SeanSun6814 — APPROVED** [review]
Everything looks good!

**Review by krpatel5657 — APPROVED** [review]
Everything looks good!

**Review by sophiajwitt — APPROVED** [review]
Looks good!

**Review by wadihPazosJr — APPROVED** [review]
Looks good!

**Pull request merged**
